(()=>{"use strict";const root=document.querySelector("[data-forecast]");if(!root)return;const title=document.querySelector("#forecast-title"),panel=root.querySelector("#panel-forecast"),tabs=[...root.querySelectorAll("[role=tab]")],grid=root.querySelector("[data-grid]"),scroll=root.querySelector("[data-scroll]"),chart=root.querySelector("[data-chart]"),chartEmpty=root.querySelector("[data-chart-empty]"),state=root.querySelector("[data-state]");const source=window.KANTO_FORECAST_DATA||{};let mode="hourly";const pad=v=>String(v).padStart(2,"0"),dateKey=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
function hourlySlots(){const supplied=Array.isArray(source.hourly)?source.hourly:[];if(supplied.length)return supplied;const now=new Date(),start=Math.floor(now.getHours()/2)*2;return Array.from({length:10},(_,i)=>{const d=new Date(now);d.setHours(start+i*2,0,0,0);return{time:d.toISOString(),placeholder:true}})}
function weeklySlots(){const supplied=Array.isArray(source.weekly)?source.weekly:[];if(supplied.length)return supplied;const today=new Date();return Array.from({length:8},(_,i)=>{const d=new Date(today);d.setDate(today.getDate()+i);return{date:dateKey(d),placeholder:true}})}
const getSlots=()=>mode==="hourly"?hourlySlots():weeklySlots();function slotDate(slot){const raw=mode==="hourly"?slot.time:slot.date;if(!raw)return null;const d=new Date(raw);return Number.isNaN(d.getTime())?null:d}
function currentIndex(slots){if(mode==="weekly"){const today=dateKey(new Date());return slots.findIndex(s=>(s.date||"").slice(0,10)===today)}if(!slots.length)return-1;const now=Date.now();let best=-1,delta=Infinity;slots.forEach((s,i)=>{const d=slotDate(s);if(!d)return;const diff=Math.abs(d.getTime()-now);if(diff<delta){delta=diff;best=i}});return best}
const fmt=(value,digits=1)=>Number.isFinite(Number(value))?Number(value).toFixed(digits):"--";function fmtTime(slot){const d=slotDate(slot);if(!d)return"--";return mode==="hourly"?`${d.getHours()}時`:`${d.getMonth()+1}/${d.getDate()}`}
function weather(slot){return slot.weather_label||slot.weather||"--"}function wave(slot){const v=slot.wave_height_m??slot.wave?.height_m;return{main:fmt(v),sub:Number.isFinite(Number(v))?"m":""}}function period(slot){const v=slot.period_s??slot.swell?.period_s;return{main:fmt(v),sub:Number.isFinite(Number(v))?"秒":""}}function wind(slot){const v=slot.wind_speed_ms??slot.wind?.speed_ms;return{main:fmt(v),sub:Number.isFinite(Number(v))?"m/s":"",direction:slot.wind_direction_label??slot.wind?.direction_label??""}}
function addCell(fragment,className,html,current=false,ariaCurrent=false){const div=document.createElement("div");div.className=`cell ${className}${current?" current":""}`;div.innerHTML=html;if(ariaCurrent)div.setAttribute("aria-current","date");fragment.appendChild(div)}
function renderGrid(){const slots=getSlots(),nowIndex=currentIndex(slots);grid.style.setProperty("--columns",slots.length);grid.replaceChildren();const rows=[{label:mode==="hourly"?"時刻":"日付",unit:"",render:s=>({main:fmtTime(s),sub:""})},{label:"天気",unit:"",render:s=>({main:weather(s),sub:""})},{label:"波の高さ",unit:"m",render:wave},{label:"周期",unit:"秒",render:period},{label:"風",unit:"m/s",render:wind}];const fragment=document.createDocumentFragment();rows.forEach((row,rowIndex)=>{addCell(fragment,"label",`${row.label}${row.unit?`<small>${row.unit}</small>`:""}`);slots.forEach((slot,index)=>{const value=row.render(slot),direction=value.direction?`<span class="wind-arrow" aria-label="風向 ${value.direction}">↑</span>`:"";addCell(fragment,"value",`${direction}<span>${value.main}</span>${value.sub?`<span class="sub">${value.sub}</span>`:""}`,index===nowIndex,rowIndex===0&&index===nowIndex)})});grid.appendChild(fragment);requestAnimationFrame(()=>{if(nowIndex>=0){const col=parseFloat(getComputedStyle(document.documentElement).getPropertyValue("--col"))||96;scroll.scrollLeft=Math.max(0,(nowIndex-1)*col)}});renderChart(slots);state.textContent=slots.some(s=>!s.placeholder)?"公開データ接続":"データ未接続"}
function renderChart(slots){const ns="http://www.w3.org/2000/svg";chart.replaceChildren();const waves=slots.map(s=>Number(s.wave_height_m??s.wave?.height_m)),winds=slots.map(s=>Number(s.wind_speed_ms??s.wind?.speed_ms)),hasWave=waves.some(Number.isFinite),hasWind=winds.some(Number.isFinite);chartEmpty.hidden=hasWave||hasWind;if(!hasWave&&!hasWind)return;const width=800,height=240,top=22,bottom=32,usable=height-top-bottom,step=slots.length>1?width/(slots.length-1):width,maxWave=Math.max(1,...waves.filter(Number.isFinite)),maxWind=Math.max(6,...winds.filter(Number.isFinite));if(hasWind)winds.forEach((v,i)=>{if(!Number.isFinite(v))return;const rect=document.createElementNS(ns,"rect"),barW=Math.max(8,Math.min(28,step*.34));rect.setAttribute("x",String(i*step-barW/2));rect.setAttribute("y",String(top+usable*(1-v/maxWind)));rect.setAttribute("width",String(barW));rect.setAttribute("height",String(usable*v/maxWind));rect.setAttribute("rx","2");rect.setAttribute("fill","#2d7281");rect.setAttribute("opacity",".75");chart.appendChild(rect)});if(hasWave){const points=waves.map((v,i)=>Number.isFinite(v)?`${i*step},${top+usable*(1-v/maxWave)}`:null).filter(Boolean);if(points.length>1){const poly=document.createElementNS(ns,"polyline");poly.setAttribute("points",points.join(" "));poly.setAttribute("fill","none");poly.setAttribute("stroke","#f45d43");poly.setAttribute("stroke-width","4");poly.setAttribute("vector-effect","non-scaling-stroke");chart.appendChild(poly)}}}
function selectMode(next,focus=false){mode=next;tabs.forEach(tab=>{const selected=tab.dataset.mode===mode;tab.classList.toggle("is-active",selected);tab.setAttribute("aria-selected",String(selected));tab.tabIndex=selected?0:-1;if(selected)panel.setAttribute("aria-labelledby",tab.id)});title.textContent=mode==="hourly"?"時間別予報":"週間予報";renderGrid();if(focus)tabs.find(tab=>tab.dataset.mode===mode)?.focus()}
tabs.forEach(tab=>{tab.addEventListener("click",()=>selectMode(tab.dataset.mode));tab.addEventListener("keydown",event=>{if(!["ArrowLeft","ArrowRight"].includes(event.key))return;event.preventDefault();selectMode(event.key==="ArrowRight"?"weekly":"hourly",true)})});selectMode("hourly")})();
